### ISSUE TITLE
write wrong value into db when there is binary string in sql.

### ISSUE THREAD

**Issue by pingworld** [alexbrainman/odbc#149]
Hi Alex,

I have a sql building like this:

```
md5str = "D64CEBB717B052D3F0B296269C3BADA831CF991F"

func toBin(s string) string {
	bins, err := hex.DecodeString(s)
	return hack.String(bins)
}

sql = fmt.Sprintf("INSERT INTO test (fid,sa) VALUES (123,'%s');", toBin(md5str))
```

when execute such sql we got an error, like this:
```
Error 1105: SQLExecute: {HY000} [MySQL][ODBC 5.3(w) Driver][mysqld-5.7.32-0ubuntu0.18.04.1]Data too long for column 'sa' at row 1
```

After debuging, we think it might be caused by [such code](https://github.com/alexbrainman/odbc/blob/f0492dfa15751dfa8566a9eda47542a084908cdb/odbcstmt.go#L42):
```
	b := api.StringToUTF16(query)
	ret = api.SQLPrepare(h, (*api.SQLWCHAR)(unsafe.Pointer(&b[0])), api.SQL_NTS)
	if IsError(ret) {
		defer releaseHandle(h)
		return nil, c.newError("SQLPrepare", h)
	}
```

Since the type of column `sa` is `varbinary(20)`, while the upper codes encode the `query` into utf16 and then save it into db, then bomb...

Like the upper case, when we change the type of `sa` into `varbinary(100)` then save successfully. But the value is not right which has been converted to `EFBFBD4CEFBFBDEFBFBD17EFBFBD52EFBFBDEFBFBDEFBFBDEFBFBD26EFBFBD3BEFBFBDEFBFBD31CF991F`.

```
mysql> select hex(sa) from test;
+--------------------------------------------------------------------------------------+
| hex(sa)                                                                            |
+--------------------------------------------------------------------------------------+
| EFBFBD4CEFBFBDEFBFBD17EFBFBD52EFBFBDEFBFBDEFBFBDEFBFBD26EFBFBD3BEFBFBDEFBFBD31CF991F |
+--------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

---

What we want to known is why do you encode the `query` into `UTF16` in `PrepareODBCStmt`?? 

And how to make it right if we still want to execute sql in such way.

Thanks for your response.

**Comment by alexbrainman** [comment]
> What we want to known is why do you encode the `query` into `UTF16` in `PrepareODBCStmt`??

ODBC SQLPrepare API function comes in 2 versions (pretty much like any WIndows API) - ascii version SQLPrepareA and utf16 version SQLPrepareW. This package always uses SQLPrepareW version, because the package wants to support any language in the world, not just limited set of English characters.

This package also assumes that all Go strings are utf8. Most of them are.

That is why it uses api.StringToUTF16 - to convert utf8 Go string into utf16 SQLPrepareW.

> And how to make it right if we still want to execute sql in such way.

I don't use MySQL server, so hard to say. But you should try []byte instead of string. Generally I don't expect this package to work properly with MySQL, because it has not been tested.

Alex

**Comment by pingworld** [comment]
Thanks for your response.

we fix it by replacing the binary string into hex string.
