### ISSUE TITLE
Cannot access remote sql server express 2014

### ISSUE THREAD

**Issue by mvbaffa** [alexbrainman/odbc#64]
Hi,

I have already enabled remote access, TCP is enabled too, of my sql server running in my windows machine.

I am running Mint 17 in VMWare hosted in the same machine of SQL Server. When I run the tests I receive login timeout and Server is not found or not accessible. The go test command is like this:

go test -mssrv="WINDOWS-MACHINE\SQLEXPR_2014" -msdb=Database -msuser=user -mspass="password" -v -run=MS -msdriver="ODBC Driver 11 for SQL Server"

Is there any sprecial issue or recomendation?

Thanks

**Comment by alexbrainman** [comment]
Do you actually use "ODBC Driver 11 for SQL Server" for Linux?

Alex

**Comment by mvbaffa** [comment]
Yes I did. I have moved inixodbc to home directory and irt worked. Thanks

**Comment by alexbrainman** [comment]
I still don't know what your issue is, but, regardless, you can check the source code (newConnParams) to see how ODBC connection string is constructed. Then you can read your ODBC driver documentaion to discover what is required. And then make appropriate changes. Ultimatly you don't have to run tests anyway. If you can use github.com/alexbrainman/odbc in your program, then it is fine as is.

Alex
